[package]
name = "simple-executor"
version = "0.1.0"
authors = ["gnzlbg <gonzalobg88@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/gnzlbg/simple-executor"

[dependencies]
crossbeam-channel = "0.3"
cfg-if = "0.1"